#ifndef MICROPHONE_CONTROLLER_SYSTEM_TYPES_WRAPPER_H
#define MICROPHONE_CONTROLLER_SYSTEM_TYPES_WRAPPER_H

#include "../../include/system_types.h"

#endif /* MICROPHONE_CONTROLLER_SYSTEM_TYPES_WRAPPER_H */
